{
  "dirContent": "./content",
  "dirMarkdown": "./content/markdown",
  "defaults": [
    {
      "name": "template",
      "val": "layout3col_vertNav.html"
    },
    {
      "name": "title",
      "val": "** Need action: No title **"
    },
    {
      "name": "type",
      "val": "page"
    },
    {
      "name": "publish_date",
      "val": "2022-01-01"
    },
    {
      "name": "feautred_img",
      "val": ""
    },
    {
      "name": "page_level",
      "val": 0
    }
  ]
}
